// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpV20oM3Y37-mZJ0uoF3QRj6rouEn5MME',
    appId: '1:24142077528:web:f656a22a5d9295fe44342d',
    messagingSenderId: '24142077528',
    projectId: 'flutterloginpage-c1cce',
    authDomain: 'flutterloginpage-c1cce.firebaseapp.com',
    storageBucket: 'flutterloginpage-c1cce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqyfmXAFiLWdh_WUYJIgygS5a6Vb46LQo',
    appId: '1:24142077528:android:32bdfc567d39f91144342d',
    messagingSenderId: '24142077528',
    projectId: 'flutterloginpage-c1cce',
    storageBucket: 'flutterloginpage-c1cce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYg36qAGbnQ2TbfngTkERiP_ZT9DNfkJo',
    appId: '1:24142077528:ios:1ca632008ab684d644342d',
    messagingSenderId: '24142077528',
    projectId: 'flutterloginpage-c1cce',
    storageBucket: 'flutterloginpage-c1cce.appspot.com',
    iosBundleId: 'com.example.ewi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYg36qAGbnQ2TbfngTkERiP_ZT9DNfkJo',
    appId: '1:24142077528:ios:a64a0e5e728df3aa44342d',
    messagingSenderId: '24142077528',
    projectId: 'flutterloginpage-c1cce',
    storageBucket: 'flutterloginpage-c1cce.appspot.com',
    iosBundleId: 'com.example.ewi.RunnerTests',
  );
}
